from vertexai.vision_models import ImageGenerationModel, ImageGenerationResponse
import os
import logging

class ImagenService:
    def __init__(self, project_id: str, location: str = "us-central1"):
        self.project_id = project_id
        self.location = location
        self.model_name = "imagen-3.0-generate-001" # Latest Imagen 3 model
        self.model = ImageGenerationModel.from_pretrained(self.model_name)

    def generate_image(self, prompt: str, output_path: str) -> bool:
        """
        Generates an image based on the prompt and saves it to output_path.
        """
        try:
            # Add style guidance for a "Memoir" feel
            enhanced_prompt = f"A beautiful, high-quality illustration in a nostalgic, cinematic style: {prompt}. Soft lighting, detailed textures, emotional atmosphere."
            
            response: ImageGenerationResponse = self.model.generate_images(
                prompt=enhanced_prompt,
                number_of_images=1,
                aspect_ratio="1:1",
                guidance_scale=21.0
            )

            if response.images:
                response.images[0].save(location=output_path, include_generation_parameters=False)
                logging.info(f"Image generated and saved to {output_path}")
                return True
            else:
                logging.warning("No images generated by Imagen.")
                return False
        except Exception as e:
            logging.error(f"Imagen generation failed: {e}")
            return False

_imagen_instance = None

def get_imagen_service() -> ImagenService:
    global _imagen_instance
    if _imagen_instance is None:
        project_id = os.getenv("GOOGLE_CLOUD_PROJECT")
        location = os.getenv("GOOGLE_CLOUD_LOCATION", "us-central1")
        if project_id:
            _imagen_instance = ImagenService(project_id, location)
        else:
            logging.warning("GOOGLE_CLOUD_PROJECT not set. Imagen service will not be available.")
    return _imagen_instance
